version: "3"

services:

  # postgresql-user:
  #   image: postgres:11-alpine
  #   environment:
  #     PGDATA                : ${PGDATA}
  #     POSTGRES_DB           : ${POSTGRES_DB}
  #     POSTGRES_USER         : ${POSTGRES_USER}
  #     POSTGRES_PASSWORD     : ${POSTGRES_PASSWORD}
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ${SQLFILES}:/docker-entrypoint-initdb.d/
  #     - ${PGDATA}:/${PGDATA}
  #   networks:
  #     - mase
  #   restart: always

  mongodb:
    image: docker-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mase
      MONGO_INITDB_ROOT_PASSWORD: mase
    restart: always
    networks: 
      - mase
    build: 
      context: .
      dockerfile: dockerfile-mongo
      args:
        - -t docker-mongo 
    

networks:
  mase:

volumes:
  pgdata-mase:
    # external: true
# executar:
# docker volume create pgdata-mase
