version: "3"

services:

  postgresql:
    environment:
      PGDATA                : ${PGDATA}
      POSTGRES_DB           : ${POSTGRES_DB}
      POSTGRES_USER         : ${POSTGRES_USER}
      POSTGRES_PASSWORD     : ${POSTGRES_PASSWORD}
      POSTGRES_FIX_OWNERSHIP: 1
    build:
      context: ./resources/database
      dockerfile: postgresql/postgresql.Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ${PGDATA}:/${PGDATA}
    networks:
      - mase
    restart: always

  mongodb:
    image: mongo:3.6-stretch
    environment:
      MONGO_INITDB_ROOT_USERNAME: mase
      MONGO_INITDB_ROOT_PASSWORD: mase
    restart: always
    networks: 
      - mase

networks:
  mase:

volumes:
  pgdata-mase:
    external: true
# executar:
# docker volume create pgdata-mase
