version: "4"

services:

  mongodb:
    image: docker-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mase
      MONGO_INITDB_ROOT_PASSWORD: mase
    restart: always
    networks: 
      - mase
    build: 
      context: .
      dockerfile: dockerfile-mongo
    
  authservice:
    image: auth-service
    networks:
      - mase
    build:
      context: ./mase-auth-service/
      dockerfile: Dockerfile 

  userservice:
    image: user-service
    networks:
      - mase
    build:
      context: ./mase-user-service/
      dockerfile: Dockerfile

  planservice:
    image: plan-service
    networks:
      - mase
    build:
      context: ./mase-plan-service/
      dockerfile: Dockerfile

  disasterservice:
    image: disaster-service
    networks:
      - mase
    build:
      context: ./mase-disaster-service/
      dockerfile: Dockerfile       

    

networks:
  mase:

volumes:
  pgdata-mase:
