version: "3"

services:

  masedb:
    image: docker-mongo
    restart: always
    networks: 
      - mase
    build: 
      context: .
      dockerfile: dockerfile-mongo
    
  authservice:
    image: auth-service
    networks:
      - mase
    build:
      context: ./mase-auth-service/
      dockerfile: Dockerfile
    ports:
      - "8380:8080"   

  userservice:
    image: user-service
    networks:
      - mase
    build:
      context: ./mase-user-service/
      dockerfile: Dockerfile
    ports:
      - "8381:8080"  

  planservice:
    image: plan-service
    networks:
      - mase
    build:
      context: ./mase-plan-service/
      dockerfile: Dockerfile
    ports:
      - "8382:8080"  

  disasterservice:
    image: disaster-service
    networks:
      - mase
    build:
      context: ./mase-disaster-service/
      dockerfile: Dockerfile
    ports:
      - "8383:8080"         


networks:
  mase:

volumes:
  pgdata-mase:
