version: "3"

services:

  mongodb:
    image: docker-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mase
      MONGO_INITDB_ROOT_PASSWORD: mase
    restart: always
    networks: 
      - mase
    build: 
      context: .
      dockerfile: dockerfile-mongo
      args:
        - -t docker-mongo 
    

networks:
  mase:

volumes:
  pgdata-mase:
