version: "3"

services:

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER         : mase
      KEYCLOAK_PASSWORD     : mase
      DB_VENDOR             : postgres
      DB_ADDR               : postgres
      DB_PORT               : 5432
      DB_DATABASE           : mase
      DB_USER               : mase
      DB_PASSWORD           : mase
      KEYCLOAK_HTTP_PORT    : 8080
    ports:
      - 8080:8080
    restart: always
    links:
      - postgres
    networks:
      - mase

  postgres:
    image: postgres:11.2
    environment:
      PGDATA                : /pgdata
      POSTGRES_DB           : mase
      POSTGRES_USER         : mase
      POSTGRES_PASSWORD     : mase
      POSTGRES_FIX_OWNERSHIP: 1
    restart: always
    volumes:
      - pgdata:/pgdata
    networks:
      - mase

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mase
      MONGO_INITDB_ROOT_PASSWORD: mase
    restart: always
    networks: 
      - mase

networks:
  mase:

volumes:
  pgdata:
    external: true
